services:
  init:
    image: init:latest
    # image: ghcr.io/nodadyoushutup/init:latest
    container_name: init
    volumes:
      - type: bind
        source: ~/.kube
        target: /opt/bitnami/kubectl/.kube
    environment:
      - NAMESPACE=radarr
      - KUBECONFIG=/opt/bitnami/kubectl/.kube/config
    command: ["/script/arr.sh"]
